-- ============================================
-- Đăng ký suất ăn - Mầm non Tam Kỳ 1
-- Supabase schema (run in SQL Editor)
-- ============================================

-- Note: auth.users is created automatically by Supabase Auth.
-- profiles references auth.users(id) and holds the app user details.

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  student_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default '',
  role text not null default 'Chưa duyệt',
  assigned_class text,
  updated_at timestamptz not null default now()
);

-- Fix tables created by the OLD schema (create table if not exists does NOT
-- update the default of an existing table).
alter table public.profiles alter column role set default 'Chưa duyệt';

-- Auto-create a profile whenever an auth user is created
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  class_name text not null,
  date date not null,
  meal_type text not null,
  count integer not null default 0,
  registered_by text,
  registered_by_id uuid,
  updated_at timestamptz not null default now(),
  unique (class_name, date, meal_type)
);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  created_by text,
  created_by_id uuid,
  read_by text[] not null default '{}'
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  timestamp timestamptz not null default now(),
  user_id uuid,
  user_name text,
  action text not null,
  details jsonb
);

create table if not exists public.archived_registrations (
  id uuid primary key default gen_random_uuid(),
  class_name text not null,
  date date not null,
  meal_type text not null,
  count integer not null default 0,
  registered_by text,
  registered_by_id uuid,
  updated_at timestamptz
);

-- ============================================
-- Auth / Role helper functions (security definer to avoid RLS recursion)
-- ============================================

create or replace function public.current_user_role()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.current_user_assigned_class()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select assigned_class from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), '') = 'Admin';
$$;

create or replace function public.is_bgh()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), '') = 'Ban Giám hiệu';
$$;

create or replace function public.is_kt_cd()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), '') = 'KT & CD';
$$;

-- Prevent non-admins from changing permission-relevant profile fields.
-- Users may update their own display_name (e.g. via signUp) but never role,
-- assigned_class or email.
create or replace function public.guard_profile_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.id <> auth.uid()) and (not public.is_admin()) then
    raise exception 'Permission denied: cannot edit this profile';
  end if;
  if not public.is_admin() and (
    new.role is distinct from old.role
    or new.assigned_class is distinct from old.assigned_class
    or new.email is distinct from old.email
  ) then
    raise exception 'Permission denied: cannot change role, class or email';
  end if;
  return new;
end;
$$;

drop trigger if exists on_profiles_update_guard on public.profiles;
create trigger on_profiles_update_guard
  before update on public.profiles
  for each row execute procedure public.guard_profile_update();

-- Prevent non-admin/BGH users from editing announcements title/content.
-- Non-privileged users may only mark announcements as read (append own id).
create or replace function public.guard_announcement_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() or public.is_bgh() then
    return new;
  end if;
  -- Only allow appending the current user's id to read_by; block all else.
  if (
    new.title is distinct from old.title
    or new.content is distinct from old.content
    or new.created_by is distinct from old.created_by
    or new.created_by_id is distinct from old.created_by_id
  ) then
    raise exception 'Permission denied: cannot edit announcement';
  end if;
  if new.read_by is distinct from old.read_by then
    if array_length(new.read_by, 1) > array_length(old.read_by, 1) then
      new.read_by := (select array_agg(distinct x order by x) from unnest(new.read_by) x);
    else
      raise exception 'Permission denied: cannot remove read status';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists on_announcements_update_guard on public.announcements;
create trigger on_announcements_update_guard
  before update on public.announcements
  for each row execute procedure public.guard_announcement_update();

-- ============================================
-- Row Level Security
-- ============================================
alter table public.classes enable row level security;
alter table public.profiles enable row level security;
alter table public.registrations enable row level security;
alter table public.announcements enable row level security;
alter table public.audit_logs enable row level security;
alter table public.archived_registrations enable row level security;

-- Read access is role-scoped so teachers only see data of their own class,
-- while Admin / BGH / KT&CD see everything relevant to their screens.
drop policy if exists "allow_read_classes" on public.classes;
create policy "allow_read_classes" on public.classes for select using (auth.role() = 'authenticated');
drop policy if exists "allow_read_profiles" on public.profiles;
create policy "allow_read_profiles" on public.profiles for select using (public.is_admin() or public.is_bgh());
drop policy if exists "allow_read_own_profile" on public.profiles;
create policy "allow_read_own_profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "allow_read_registrations" on public.registrations;
create policy "allow_read_registrations" on public.registrations for select using (
  public.is_admin() or public.is_bgh() or public.is_kt_cd()
  or (
    public.current_user_role() = 'Giáo viên'
    and public.current_user_assigned_class() = class_name
  )
);
drop policy if exists "allow_read_announcements" on public.announcements;
create policy "allow_read_announcements" on public.announcements for select using (auth.role() = 'authenticated');
drop policy if exists "allow_read_audit_logs" on public.audit_logs;
create policy "allow_read_audit_logs" on public.audit_logs for select using (public.is_admin());
drop policy if exists "allow_read_archived" on public.archived_registrations;
create policy "allow_read_archived" on public.archived_registrations for select using (public.is_admin());

-- Writes: enforced by role (business rules live in the application AND here).

-- ---- classes: Admin only ----
drop policy if exists "allow_write_classes" on public.classes;
drop policy if exists "admin_write_classes" on public.classes;
create policy "admin_write_classes" on public.classes
  for all using (public.is_admin()) with check (public.is_admin());

-- ---- profiles: update own (guarded) or admin; delete admin only ----
drop policy if exists "allow_write_profiles" on public.profiles;
drop policy if exists "user_update_own_profile" on public.profiles;
create policy "user_update_own_profile" on public.profiles
  for update using (auth.uid() = id or public.is_admin())
  with check (auth.uid() = id or public.is_admin());
drop policy if exists "admin_delete_profiles" on public.profiles;
create policy "admin_delete_profiles" on public.profiles
  for delete using (public.is_admin());

-- ---- registrations: Admin / KT&CD any class, GV only own class ----
drop policy if exists "allow_write_registrations" on public.registrations;
drop policy if exists "admin_write_registrations" on public.registrations;
create policy "admin_write_registrations" on public.registrations
  for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "kt_write_registrations" on public.registrations;
create policy "kt_write_registrations" on public.registrations
  for all using (public.is_kt_cd()) with check (public.is_kt_cd());
drop policy if exists "gv_write_own_class_registrations" on public.registrations;
create policy "gv_write_own_class_registrations" on public.registrations
  for all using (
    public.current_user_role() = 'Giáo viên'
    and public.current_user_assigned_class() = class_name
  )
  with check (
    public.current_user_role() = 'Giáo viên'
    and public.current_user_assigned_class() = class_name
  );

-- ---- announcements: Admin / BGH manage; others read only (mark-as-read via trigger) ----
drop policy if exists "allow_write_announcements" on public.announcements;
drop policy if exists "admin_bgh_write_announcements" on public.announcements;
create policy "admin_bgh_write_announcements" on public.announcements
  for all using (public.is_admin() or public.is_bgh())
  with check (public.is_admin() or public.is_bgh());
drop policy if exists "authenticated_read_announcement" on public.announcements;
create policy "authenticated_read_announcement" on public.announcements
  for update using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- ---- audit_logs: any authenticated may insert; Admin deletes ----
drop policy if exists "allow_write_audit_logs" on public.audit_logs;
drop policy if exists "authenticated_insert_audit_logs" on public.audit_logs;
create policy "authenticated_insert_audit_logs" on public.audit_logs
  for insert with check (auth.role() = 'authenticated');
drop policy if exists "admin_delete_audit_logs" on public.audit_logs;
create policy "admin_delete_audit_logs" on public.audit_logs
  for delete using (public.is_admin());

-- ---- archived_registrations: Admin only ----
drop policy if exists "allow_write_archived" on public.archived_registrations;
drop policy if exists "admin_write_archived" on public.archived_registrations;
create policy "admin_write_archived" on public.archived_registrations
  for all using (public.is_admin()) with check (public.is_admin());

-- ============================================
-- Performance indexes (matters as the user base grows)
-- ============================================
create index if not exists idx_registrations_date_class on public.registrations (date desc, class_name);
create index if not exists idx_audit_logs_timestamp on public.audit_logs (timestamp desc);
create index if not exists idx_announcements_created_at on public.announcements (created_at desc);

-- ============================================
-- Realtime (idempotent: skip tables already in the publication)
-- ============================================
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'classes') then
    alter publication supabase_realtime add table public.classes;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'profiles') then
    alter publication supabase_realtime add table public.profiles;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'announcements') then
    alter publication supabase_realtime add table public.announcements;
  end if;
end$$;

-- ============================================
-- RPC: Archive registrations of a month
-- ============================================
create or replace function public.archive_registrations(p_start date, p_end date)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if not public.is_admin() then
    raise exception 'Permission denied: admin only';
  end if;
  insert into public.archived_registrations (class_name, date, meal_type, count, registered_by, registered_by_id, updated_at)
  select class_name, date, meal_type, count, registered_by, registered_by_id, updated_at
  from public.registrations
  where date >= p_start and date <= p_end;

  get diagnostics v_count = row_count;

  delete from public.registrations where date >= p_start and date <= p_end;

  return v_count;
end;
$$;

-- ============================================
-- RPC: Delete an auth user + profile (by admin)
-- ============================================
create or replace function public.delete_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Permission denied: admin only';
  end if;
  delete from auth.users where id = p_user_id;
end;
$$;

-- ============================================
-- RPC: Classes already registered for a date (any authenticated user)
-- Returns only class names, so teachers can see the summary count
-- without being able to read other classes' meal counts.
-- ============================================
create or replace function public.get_registered_classes(p_date date)
returns table(class_name text)
language sql
security definer
set search_path = public
stable
as $$
  select r.class_name
  from public.registrations r
  where r.date = p_date
    and r.count > 0
    and r.meal_type in ('Bữa trưa (trẻ)', 'Bữa trưa (GV)')
  group by r.class_name;
$$;

grant execute on function public.get_registered_classes(date) to authenticated;
