-- ============================================
-- Đăng ký suất ăn - Mầm non Tam Kỳ 1
-- Supabase schema (run in SQL Editor)
-- ============================================

-- Note: auth.users is created automatically by Supabase Auth.
-- profiles references auth.users(id) and holds the app user details.

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  student_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default '',
  role text not null default 'Chưa duyệt',
  assigned_class text,
  updated_at timestamptz not null default now()
);

-- Fix tables created by the OLD schema (create table if not exists does NOT
-- update the default of an existing table).
alter table public.profiles alter column role set default 'Chưa duyệt';

-- Sĩ số: suất ăn của trẻ (bữa trưa & bữa mai) không được vượt quá sĩ số lớp.
-- Chạy cho cả INSERT (đăng ký trực tiếp) lẫn UPDATE (kể cả qua RPC ghi/lock).
create or replace function public.enforce_registration_capacity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student_count integer;
begin
  if new.meal_type in ('Bữa trưa (trẻ)', 'Bữa mai (trẻ)') then
    select coalesce(student_count, 0) into v_student_count
    from public.classes
    where name = new.class_name;
    if new.count > v_student_count then
      raise exception 'Số lượng suất ăn của trẻ vượt quá sĩ số lớp.' using errcode = 'P0001';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_registration_capacity_trigger on public.registrations;
create trigger enforce_registration_capacity_trigger
before insert or update on public.registrations
for each row
execute function public.enforce_registration_capacity();

-- Auto-create a profile whenever an auth user is created.
-- Idempotent: if a profile already exists (duplicate/retry), it just syncs the
-- email + display name without touching role/class (which are set by admins).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, ''), '@', 1))
  )
  on conflict (id) do update
  set email = excluded.email,
      display_name = case
        when coalesce(excluded.display_name, '') = '' then public.profiles.display_name
        else excluded.display_name
      end;
  return new;
end;
$$;

-- Keep the profile email in sync when the user changes their email in Auth.
create or replace function public.sync_auth_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
  set email = new.email,
      updated_at = now()
  where id = new.id
    and email is distinct from new.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_updated on auth.users;
create trigger on_auth_user_updated
  after update on auth.users
  for each row execute procedure public.sync_auth_user_profile();

-- Backfill: ensure every existing auth user has a profile row, so no user is
-- left without a profile even if the trigger was added later. Idempotent.
insert into public.profiles (id, email, display_name)
select
  u.id,
  u.email,
  coalesce(u.raw_user_meta_data ->> 'display_name', split_part(coalesce(u.email, ''), '@', 1))
from auth.users u
on conflict (id) do update
set email = excluded.email;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  class_name text not null,
  date date not null,
  meal_type text not null,
  count integer not null default 0,
  registered_by text,
  registered_by_id uuid,
  updated_at timestamptz not null default now(),
  unique (class_name, date, meal_type)
);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  created_by text,
  created_by_id uuid,
  read_by text[] not null default '{}'
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  timestamp timestamptz not null default now(),
  user_id uuid,
  user_name text,
  action text not null,
  details jsonb
);

create table if not exists public.archived_registrations (
  id uuid primary key default gen_random_uuid(),
  class_name text not null,
  date date not null,
  meal_type text not null,
  count integer not null default 0,
  registered_by text,
  registered_by_id uuid,
  updated_at timestamptz
);

-- ============================================
-- Auth / Role helper functions (security definer to avoid RLS recursion)
-- ============================================

create or replace function public.current_user_role()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.current_user_assigned_class()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select assigned_class from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), '') = 'Admin';
$$;

create or replace function public.is_bgh()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), '') = 'Ban Giám hiệu';
$$;

create or replace function public.is_kt_cd()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), '') = 'KT & CD';
$$;

-- Prevent non-admins from changing permission-relevant profile fields.
-- Users may update their own display_name (e.g. via signUp) but never role,
-- assigned_class or email.
create or replace function public.guard_profile_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.id <> auth.uid()) and (not public.is_admin()) then
    raise exception 'Permission denied: cannot edit this profile';
  end if;
  if not public.is_admin() and (
    new.role is distinct from old.role
    or new.assigned_class is distinct from old.assigned_class
    or new.email is distinct from old.email
  ) then
    raise exception 'Permission denied: cannot change role, class or email';
  end if;
  return new;
end;
$$;

drop trigger if exists on_profiles_update_guard on public.profiles;
create trigger on_profiles_update_guard
  before update on public.profiles
  for each row execute procedure public.guard_profile_update();

-- Prevent non-admin/BGH users from editing announcements title/content.
-- Non-privileged users may only mark announcements as read (append own id).
create or replace function public.guard_announcement_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() or public.is_bgh() then
    return new;
  end if;
  -- Only allow appending the current user's id to read_by; block all else.
  if (
    new.title is distinct from old.title
    or new.content is distinct from old.content
    or new.created_by is distinct from old.created_by
    or new.created_by_id is distinct from old.created_by_id
  ) then
    raise exception 'Permission denied: cannot edit announcement';
  end if;
  if new.read_by is distinct from old.read_by then
    if array_length(new.read_by, 1) > array_length(old.read_by, 1) then
      new.read_by := (select array_agg(distinct x order by x) from unnest(new.read_by) x);
    else
      raise exception 'Permission denied: cannot remove read status';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists on_announcements_update_guard on public.announcements;
create trigger on_announcements_update_guard
  before update on public.announcements
  for each row execute procedure public.guard_announcement_update();

-- ============================================
-- Row Level Security
-- ============================================
alter table public.classes enable row level security;
alter table public.profiles enable row level security;
alter table public.registrations enable row level security;
alter table public.announcements enable row level security;
alter table public.audit_logs enable row level security;
alter table public.archived_registrations enable row level security;

-- Read access is role-scoped so teachers only see data of their own class,
-- while Admin / BGH / KT&CD see everything relevant to their screens.
drop policy if exists "allow_read_classes" on public.classes;
create policy "allow_read_classes" on public.classes for select using (auth.role() = 'authenticated');
drop policy if exists "allow_read_profiles" on public.profiles;
create policy "allow_read_profiles" on public.profiles for select using (public.is_admin() or public.is_bgh());
drop policy if exists "allow_read_own_profile" on public.profiles;
create policy "allow_read_own_profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "allow_read_registrations" on public.registrations;
create policy "allow_read_registrations" on public.registrations for select using (
  public.is_admin() or public.is_bgh() or public.is_kt_cd()
  or (
    public.current_user_role() = 'Giáo viên'
    and public.current_user_assigned_class() = class_name
  )
);
drop policy if exists "allow_read_announcements" on public.announcements;
-- Announcements are read through the get_announcements RPC (strips reader IDs
-- for non-admins), or directly by admins/BGH. No broad select policy.
drop policy if exists "allow_read_audit_logs" on public.audit_logs;
create policy "allow_read_audit_logs" on public.audit_logs for select using (public.is_admin());
drop policy if exists "allow_read_archived" on public.archived_registrations;
create policy "allow_read_archived" on public.archived_registrations for select using (public.is_admin());

-- Writes: enforced by role (business rules live in the application AND here).

-- ---- classes: Admin only ----
drop policy if exists "allow_write_classes" on public.classes;
drop policy if exists "admin_write_classes" on public.classes;
create policy "admin_write_classes" on public.classes
  for all using (public.is_admin()) with check (public.is_admin());

-- ---- profiles: update own (guarded) or admin; delete admin only ----
drop policy if exists "allow_write_profiles" on public.profiles;
drop policy if exists "user_update_own_profile" on public.profiles;
create policy "user_update_own_profile" on public.profiles
  for update using (auth.uid() = id or public.is_admin())
  with check (auth.uid() = id or public.is_admin());
drop policy if exists "admin_delete_profiles" on public.profiles;
create policy "admin_delete_profiles" on public.profiles
  for delete using (public.is_admin());

-- ---- registrations: Admin / KT&CD any class, GV only own class ----
drop policy if exists "allow_write_registrations" on public.registrations;
drop policy if exists "admin_write_registrations" on public.registrations;
create policy "admin_write_registrations" on public.registrations
  for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "kt_write_registrations" on public.registrations;
create policy "kt_write_registrations" on public.registrations
  for all using (public.is_kt_cd()) with check (public.is_kt_cd());
drop policy if exists "gv_write_own_class_registrations" on public.registrations;
create policy "gv_write_own_class_registrations" on public.registrations
  for all using (
    public.current_user_role() = 'Giáo viên'
    and public.current_user_assigned_class() = class_name
  )
  with check (
    public.current_user_role() = 'Giáo viên'
    and public.current_user_assigned_class() = class_name
  );

-- ---- announcements: Admin / BGH manage (read + write); others read via get_announcements RPC ----
drop policy if exists "allow_write_announcements" on public.announcements;
drop policy if exists "admin_bgh_write_announcements" on public.announcements;
drop policy if exists "authenticated_read_announcement" on public.announcements;
drop policy if exists "authed_update_announcements" on public.announcements;
drop policy if exists "authed_read_announcements" on public.announcements;
drop policy if exists "read_announcements_admin_only" on public.announcements;
drop policy if exists "admin_bgh_update_announcements" on public.announcements;
create policy "admin_bgh_write_announcements" on public.announcements
  for all using (public.is_admin() or public.is_bgh())
  with check (public.is_admin() or public.is_bgh());

-- ---- audit_logs: any authenticated may insert (must record the acting user); Admin deletes ----
drop policy if exists "allow_write_audit_logs" on public.audit_logs;
drop policy if exists "authenticated_insert_audit_logs" on public.audit_logs;
create policy "authenticated_insert_audit_logs" on public.audit_logs
  for insert with check (
    auth.role() = 'authenticated'
    and user_id = auth.uid()
  );
drop policy if exists "admin_delete_audit_logs" on public.audit_logs;
create policy "admin_delete_audit_logs" on public.audit_logs
  for delete using (public.is_admin());

-- Audit log integrity: user_id must always match the acting user, and the row
-- cannot be edited after insert (append-only history of who did what).
drop policy if exists "no_update_audit_logs" on public.audit_logs;
create policy "no_update_audit_logs" on public.audit_logs
  for update using (false) with check (false);

-- ---- archived_registrations: Admin only ----
drop policy if exists "allow_write_archived" on public.archived_registrations;
drop policy if exists "admin_write_archived" on public.archived_registrations;
create policy "admin_write_archived" on public.archived_registrations
  for all using (public.is_admin()) with check (public.is_admin());

-- ============================================
-- Performance indexes (matters as the user base grows)
-- ============================================
create index if not exists idx_registrations_date_class on public.registrations (date desc, class_name);
create index if not exists idx_registrations_class on public.registrations (class_name);
create index if not exists idx_archived_date_class on public.archived_registrations (date desc, class_name);
create index if not exists idx_archived_class on public.archived_registrations (class_name);
create index if not exists idx_audit_logs_timestamp on public.audit_logs (timestamp desc);
create index if not exists idx_announcements_created_at on public.announcements (created_at desc);

-- ============================================
-- Realtime (idempotent: skip tables already in the publication)
-- ============================================
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'classes') then
    alter publication supabase_realtime add table public.classes;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'profiles') then
    alter publication supabase_realtime add table public.profiles;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'announcements') then
    alter publication supabase_realtime add table public.announcements;
  end if;
end$$;

-- ============================================
-- RPC: Archive registrations of a month
-- ============================================
create or replace function public.archive_registrations(p_start date, p_end date)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if not public.is_admin() then
    raise exception 'Permission denied: admin only';
  end if;
  insert into public.archived_registrations (class_name, date, meal_type, count, registered_by, registered_by_id, updated_at)
  select class_name, date, meal_type, count, registered_by, registered_by_id, updated_at
  from public.registrations
  where date >= p_start and date <= p_end;

  get diagnostics v_count = row_count;

  delete from public.registrations where date >= p_start and date <= p_end;

  return v_count;
end;
$$;

revoke execute on function public.archive_registrations(date, date) from public;
grant execute on function public.archive_registrations(date, date) to authenticated;

-- ============================================
-- RPC: Delete an auth user + profile (by admin)
-- ============================================
create or replace function public.delete_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Permission denied: admin only';
  end if;
  delete from auth.users where id = p_user_id;
end;
$$;

revoke execute on function public.delete_user(uuid) from public;
grant execute on function public.delete_user(uuid) to authenticated;

-- ============================================
-- RPC: Classes already registered for a date (any authenticated user)
-- Returns only class names, so teachers can see the summary count
-- without being able to read other classes' meal counts.
-- ============================================
create or replace function public.get_registered_classes(p_date date)
returns table(class_name text)
language sql
security definer
set search_path = public
stable
as $$
  select r.class_name
  from public.registrations r
  where r.date = p_date
    and r.count > 0
    and r.meal_type in ('Bữa trưa (trẻ)', 'Bữa trưa (GV)')
  group by r.class_name;
$$;

revoke execute on function public.get_registered_classes(date) from public;
grant execute on function public.get_registered_classes(date) to authenticated;

-- ============================================
-- RPC: Atomic save of an edit session (staleness check + writes in ONE transaction)
-- Prevents two users overwriting each other and avoids partial writes.
-- p_updates:   [{id, count, registered_by_id, registered_by}]  -> existing rows
-- p_upserts:   [{class_name, date, meal_type, count, registered_by_id, registered_by}]
-- p_delete_ids: uuid[]                                         -> existing rows to delete
-- p_originals: [{id, updated_at}]                              -> version check; NULL = skip check
-- Raises 'STALE_DATA' if any row changed since the client fetched it.
-- ============================================
create or replace function public.save_registrations(
  p_updates jsonb,
  p_upserts jsonb,
  p_delete_ids uuid[],
  p_originals jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text := public.current_user_role();
  v_class text := public.current_user_assigned_class();
  v_id uuid;
  v_upd timestamptz;
  v_client timestamptz;
  v_now timestamptz := now();
  v_class_name text;
  v_date date;
  v_meal text;
  v_count integer;
  v_rid uuid;
  v_rname text;
begin
  -- Permission: Admin / KT_CD any class; GV only own class.
  if v_role not in ('Admin', 'KT & CD', 'Giáo viên') then
    raise exception 'Bạn không có quyền cập nhật đăng ký.' using errcode = '42501';
  end if;

  if v_role = 'Giáo viên' then
    if exists (
      select 1
      from jsonb_to_recordset(coalesce(p_upserts, '[]'::jsonb)) as u(class_name text)
      where u.class_name is distinct from v_class
    ) then
      raise exception 'Bạn chỉ được chỉnh sửa suất ăn cho lớp được phân công.' using errcode = '42501';
    end if;
    if exists (
      select 1
      from public.registrations r
      where ((r.id = any(coalesce(p_delete_ids, '{}'::uuid[])))
          or (r.id in (select (x.value ->> 'id')::uuid from jsonb_array_elements(coalesce(p_updates, '[]'::jsonb)) x)))
        and r.class_name is distinct from v_class
    ) then
      raise exception 'Bạn chỉ được chỉnh sửa suất ăn cho lớp được phân công.' using errcode = '42501';
    end if;
  end if;

  -- STALE_DATA check under row locks.
  for v_id in
    select (x.value ->> 'id')::uuid
    from jsonb_array_elements(coalesce(p_originals, '[]'::jsonb)) x
  loop
    select r.updated_at into v_upd
    from public.registrations r
    where r.id = v_id
    for update;
    if not found then
      raise exception 'STALE_DATA' using errcode = 'P0001';
    end if;
    select (x.value ->> 'updated_at')::timestamptz into v_client
    from jsonb_array_elements(coalesce(p_originals, '[]'::jsonb)) x
    where (x.value ->> 'id')::uuid = v_id;
    -- Compare at millisecond precision: Postgres stores microseconds while the
    -- client serializes updated_at via JS Date (millisecond precision), so a
    -- full-precision comparison would always report STALE_DATA on untouched rows.
    if v_client is not null and date_trunc('milliseconds', v_upd) is distinct from date_trunc('milliseconds', v_client) then
      raise exception 'STALE_DATA' using errcode = 'P0001';
    end if;
  end loop;

  -- Upserts (rows created or re-created during the edit).
  for v_class_name, v_date, v_meal, v_count, v_rid, v_rname in
    select u.class_name, u.date, u.meal_type, u.count, u.registered_by_id, u.registered_by
    from jsonb_to_recordset(coalesce(p_upserts, '[]'::jsonb))
      as u(class_name text, date date, meal_type text, count integer,
           registered_by_id uuid, registered_by text)
  loop
    insert into public.registrations (class_name, date, meal_type, count, registered_by_id, registered_by, updated_at)
    values (v_class_name, v_date, v_meal, v_count, v_rid, v_rname, v_now)
    on conflict (class_name, date, meal_type) do update
      set count = excluded.count,
          registered_by_id = excluded.registered_by_id,
          registered_by = excluded.registered_by,
          updated_at = v_now;
  end loop;

  -- Updates of existing rows.
  for v_id in
    select (x.value ->> 'id')::uuid
    from jsonb_array_elements(coalesce(p_updates, '[]'::jsonb)) x
  loop
    update public.registrations r
    set count = (x.value ->> 'count')::integer,
        registered_by_id = coalesce((x.value ->> 'registered_by_id')::uuid, r.registered_by_id),
        registered_by = coalesce((x.value ->> 'registered_by')::text, r.registered_by),
        updated_at = v_now
    from jsonb_array_elements(coalesce(p_updates, '[]'::jsonb)) x
    where r.id = v_id;
  end loop;

  -- Deletes.
  if coalesce(array_length(p_delete_ids, 1), 0) > 0 then
    delete from public.registrations where id = any(p_delete_ids);
  end if;
end;
$$;

revoke execute on function public.save_registrations(jsonb, jsonb, uuid[], jsonb) from public;
grant execute on function public.save_registrations(jsonb, jsonb, uuid[], jsonb) to authenticated;

-- ============================================
-- RPC: Rename a class atomically across all tables that reference the name.
-- Keeps teacher assignments (profiles.assigned_class), live registrations and
-- archived registrations in sync in a single transaction.
-- ============================================
create or replace function public.rename_class(p_old_name text, p_new_name text, p_student_count integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Permission denied: admin only' using errcode = '42501';
  end if;
  if p_old_name = p_new_name then
    -- Only the student count changed.
    update public.classes set student_count = coalesce(p_student_count, student_count) where name = p_old_name;
    return;
  end if;
  if exists (select 1 from public.classes where name = p_new_name) then
    raise exception 'Tên lớp đã tồn tại.' using errcode = '23505';
  end if;

  update public.classes
  set name = p_new_name, student_count = coalesce(p_student_count, student_count)
  where name = p_old_name;
  if not found then
    raise exception 'Không tìm thấy lớp.' using errcode = 'P0002';
  end if;

  update public.registrations set class_name = p_new_name where class_name = p_old_name;
  update public.archived_registrations set class_name = p_new_name where class_name = p_old_name;
  update public.profiles set assigned_class = p_new_name where assigned_class = p_old_name;
end;
$$;

revoke execute on function public.rename_class(text, text, integer) from public;
grant execute on function public.rename_class(text, text, integer) to authenticated;

-- ============================================
-- RPC: Read announcements with privacy-safe read_by.
-- Admin / BGH (who manage readership) get the full list of reader IDs.
-- Everyone else only sees their own read state, so other users' internal UUIDs
-- are never exposed. `total` is the global announcement count (for pagination).
-- Order is newest first (matches the previous direct query).
-- ============================================
create or replace function public.get_announcements(p_limit integer)
returns table(
  id uuid,
  title text,
  content text,
  created_at timestamptz,
  created_by text,
  created_by_id uuid,
  read_by text[],
  total bigint
)
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_total bigint;
begin
  select count(*) into v_total from public.announcements;

  if public.is_admin() or public.is_bgh() then
    return query
      select a.id, a.title, a.content, a.created_at, a.created_by, a.created_by_id,
             coalesce(a.read_by, '{}'::text[]) as read_by,
             v_total as total
      from public.announcements a
      order by a.created_at desc
      limit p_limit;
  else
    return query
      select a.id, a.title, a.content, a.created_at, a.created_by, a.created_by_id,
             case when (auth.uid()::text = any(coalesce(a.read_by, '{}'::text[])))
                  then array[auth.uid()::text]
                  else '{}'::text[]
             end as read_by,
             v_total as total
      from public.announcements a
      order by a.created_at desc
      limit p_limit;
  end if;
end;
$$;

revoke execute on function public.get_announcements(integer) from public;
grant execute on function public.get_announcements(integer) to authenticated;

drop policy if exists "allow_read_announcements" on public.announcements;
drop policy if exists "authed_read_announcements" on public.announcements;
drop policy if exists "read_announcements_admin_only" on public.announcements;
-- Direct reads of the announcements table (including the sensitive read_by column)
-- are limited to admins/BGH. Everyone else reads via the get_announcements RPC,
-- which strips other users' reader IDs.
create policy "read_announcements_admin_only" on public.announcements
  for select using (public.is_admin() or public.is_bgh());

-- ============================================
-- RPC: Atomically mark the current user as a reader of an announcement.
-- Server-side counterpart to the read_by column, keeps the user's read state
-- private (no need for the client to read the full reader list).
-- ============================================
create or replace function public.mark_announcement_read(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid text := auth.uid()::text;
begin
  if v_uid is null then
    raise exception 'Not authenticated' using errcode = '42501';
  end if;
  update public.announcements
  set read_by = (
    select array_agg(distinct x order by x)
    from unnest(
      case when v_uid = any(coalesce(read_by, '{}'::text[]))
           then read_by
           else array_append(coalesce(read_by, '{}'::text[]), v_uid)
      end
    ) x
  )
  where id = p_id;
end;
$$;

revoke execute on function public.mark_announcement_read(uuid) from public;
grant execute on function public.mark_announcement_read(uuid) to authenticated;
